---
baseURL: "https://socialcars.github.io/"
title: "SocialCars"
footnoteReturnLinkContents: "↩"
languageCode: "en-us"
paginate: 10
theme: "mainroad"
# permalinks:
#   post: /:year/:month/:title/
params:
  contact : "info@socialcars.org"
  license : "https://creativecommons.org/licenses/by-sa/4.0/"
  domain:
    protocol : "https://"
    name : "socialcars.github.io"
  subtitle: "Cooperative (de-&#x2060;)centralized traffic management"
  description: "DFG Research Training Group 1931"
  opengraph: true
  leftsidebar: false # Move sidebar to the left side if true
  hidesidebar: true
  authorbox: false
  post_navigation: false
  widgets:
    search: false # Enable "Search" widget
    recent_articles: false # Enable "Recent articles" widget
    recent_articles_num: 10 # Set the number of articles in the "Recent articles" widget
    categories: false # Enable "Categories" widget
    tags: false # Enable "Tags" widget
    tags_counter: false # Enable counter for each tag in "Tags" widget (disabled by default)
    social: false # Enable "Social" widget
    social_github: "socialcars"
    social_email: "info@socialcars.org"