---
baseURL: "https://socialcars.github.io/"
title: "SocialCars - Development and Documentation Website of DFG Research Training Group 1931"
footnoteReturnLinkContents: "↩"
languageCode: "en-GB"
defaultContentLanguage: "en-GB"
paginate: 10
theme: "mainroad"
enableEmoji: true
enableRobotsTXT: true

# permalinks:
#   post: /:year/:month/:title/
params:
  contact : "info@socialcars.org"
  license : "https://creativecommons.org/licenses/by-sa/4.0/"
  domain:
    protocol : "https://"
    name : "socialcars.github.io"
  icon:
    logo: "images/logo.png"
  keywords: "social, cars, simulation, research, documentation, source code, socialcars, vehicle, traffic, system, driver, traffic management, cooperative traffic management, research training group, dfg, 1931, decentralized"
  logotitle: "SocialCars"
  subtitle: "Cooperative (de-&#x2060;)centralized traffic management"
  description: "DFG Research Training Group 1931"
  metadescription: "The focus of SocialCars is on significantly improving future urban road traffic, through cooperative approaches. “How can individual travelers make optimal use of the transport infrastructure, so that safety is increased and congestion and pollution are reduced?” is the key question. SocialCars aims to answer this question by investigating the interaction between centralized (system-optimal) management and decentralized (user-optimal) decisions of traffic participants."
  googleverify: "rVgMp8wUHt7-Xvhp2bhVQC_8dklPQGZ16VRqyrumqvE"
  opengraph: true
  leftsidebar: false # Move sidebar to the left side if true
  hidesidebar: true
  authorbox: false
  post_navigation: false
  widgets:
    search: false # Enable "Search" widget
    recent_articles: false # Enable "Recent articles" widget
    recent_articles_num: 10 # Set the number of articles in the "Recent articles" widget
    categories: false # Enable "Categories" widget
    tags: false # Enable "Tags" widget
    tags_counter: false # Enable counter for each tag in "Tags" widget (disabled by default)
    social: false # Enable "Social" widget
    social_github: "socialcars"
    social_email: "info@socialcars.org"